import { INTERIOR_MODELS } from './catalog.data';

/**
 * One interior model from the Quaternius "Ultimate House Interior" CC0 pack
 * (see PROVENANCE.md). The GLBs live under `public/models/interior/`; the
 * manifest in `catalog.data.ts` is generated by `scripts/convert-interior.cjs`.
 */
export interface InteriorModelEntry {
  /** Stable id = source filename stem, e.g. `Bathroom_Bathtub`. */
  readonly id: string;
  /** GLB filename under `public/models/interior/`. */
  readonly file: string;
  /** Category = id prefix before the first underscore, e.g. `Bathroom`. */
  readonly category: string;
  /** Bounding-box size in source units (normalized to the grid by the registry). */
  readonly dims: { readonly x: number; readonly y: number; readonly z: number };
}

/** The full interior-model catalog. */
export const interiorModels: readonly InteriorModelEntry[] =
  INTERIOR_MODELS as readonly InteriorModelEntry[];

/** Look up a model by id; `undefined` if unknown. */
export function interiorModelById(id: string): InteriorModelEntry | undefined {
  return interiorModels.find((m) => m.id === id);
}

/** All distinct categories present in the catalog, sorted. */
export function interiorCategories(): string[] {
  return [...new Set(interiorModels.map((m) => m.category))].sort();
}

/** All models in a category (e.g. `Bed`, `Couch`), in catalog order. */
export function interiorModelsByCategory(category: string): InteriorModelEntry[] {
  return interiorModels.filter((m) => m.category === category);
}

/**
 * Floor footprint in grid cells at the given cell size, from the model's x/z
 * bounding box (y is up). At least 1×1. Pass the live `CELL_SIZE` so this stays
 * correct across a grid-pitch change.
 */
export function footprintCells(
  model: InteriorModelEntry,
  cellSize: number,
): { x: number; z: number } {
  return {
    x: Math.max(1, Math.ceil(model.dims.x / cellSize)),
    z: Math.max(1, Math.ceil(model.dims.z / cellSize)),
  };
}

/** Per-model normalization override applied at render time. */
export interface ModelNormalization {
  /** Uniform scale to apply to source units (default 1). */
  scale?: number;
  /** Yaw (degrees about +Y) to reorient the model (default 0). */
  yawDeg?: number;
}

/**
 * Per-model normalization overrides, keyed by model id. Empty by default — the
 * Quaternius models are upright and roughly metric, so identity is the baseline;
 * entries are added here after visual inspection (e.g. a model authored at the
 * wrong scale or facing). Floor-seating (sitting the model on y=0) is derived
 * from the loaded bounding box at render time, not stored here.
 */
export const INTERIOR_NORMALIZATION: Readonly<Record<string, ModelNormalization>> = {};

/**
 * Uniform scale applied to every interior model unless a per-id entry overrides
 * it. The Quaternius pack is authored at ~2 source units per metre, so 0.5 brings
 * models to metric (a single bed reads ~1 × 2 m). Fine-tune per-id in the registry.
 */
export const INTERIOR_SCALE = 0.5;

/** Normalization override for a model id (the global scale unless overridden). */
export function normalizationOverride(id: string): ModelNormalization {
  return { scale: INTERIOR_SCALE, ...INTERIOR_NORMALIZATION[id] };
}
