// GENERATED by scripts/convert-interior.cjs — do not edit by hand.
// Source: Quaternius "Ultimate House Interior" (CC0). See PROVENANCE.md.
// Re-generate: node scripts/convert-interior.cjs

export const INTERIOR_MODELS = [
  {
    "id": "Bathroom_Bathtub",
    "file": "Bathroom_Bathtub.glb",
    "category": "Bathroom",
    "dims": {
      "x": 1.608,
      "y": 1.26,
      "z": 3.9
    }
  },
  {
    "id": "Bathroom_Mirror1",
    "file": "Bathroom_Mirror1.glb",
    "category": "Bathroom",
    "dims": {
      "x": 0.648,
      "y": 0.93,
      "z": 0.102
    }
  },
  {
    "id": "Bathroom_Mirror2",
    "file": "Bathroom_Mirror2.glb",
    "category": "Bathroom",
    "dims": {
      "x": 0.537,
      "y": 0.774,
      "z": 0.038
    }
  },
  {
    "id": "Bathroom_Shower1",
    "file": "Bathroom_Shower1.glb",
    "category": "Bathroom",
    "dims": {
      "x": 1.896,
      "y": 3.548,
      "z": 1.893
    }
  },
  {
    "id": "Bathroom_Sink",
    "file": "Bathroom_Sink.glb",
    "category": "Bathroom",
    "dims": {
      "x": 1.39,
      "y": 1.447,
      "z": 0.815
    }
  },
  {
    "id": "Bathroom_Toilet",
    "file": "Bathroom_Toilet.glb",
    "category": "Bathroom",
    "dims": {
      "x": 1.197,
      "y": 1.901,
      "z": 1.691
    }
  },
  {
    "id": "Bathroom_Toilet2",
    "file": "Bathroom_Toilet2.glb",
    "category": "Bathroom",
    "dims": {
      "x": 1.111,
      "y": 1.008,
      "z": 1.54
    }
  },
  {
    "id": "Bathroom_ToiletPaper",
    "file": "Bathroom_ToiletPaper.glb",
    "category": "Bathroom",
    "dims": {
      "x": 0.3,
      "y": 0.344,
      "z": 0.175
    }
  },
  {
    "id": "Bathroom_ToiletPaperPile",
    "file": "Bathroom_ToiletPaperPile.glb",
    "category": "Bathroom",
    "dims": {
      "x": 0.334,
      "y": 0.375,
      "z": 0.35
    }
  },
  {
    "id": "Bathroom_Towel",
    "file": "Bathroom_Towel.glb",
    "category": "Bathroom",
    "dims": {
      "x": 1.185,
      "y": 0.654,
      "z": 0.161
    }
  },
  {
    "id": "Bathroom_WashingMachine",
    "file": "Bathroom_WashingMachine.glb",
    "category": "Bathroom",
    "dims": {
      "x": 1.292,
      "y": 1.47,
      "z": 1.324
    }
  },
  {
    "id": "Bed_Bunk",
    "file": "Bed_Bunk.glb",
    "category": "Bed",
    "dims": {
      "x": 2.169,
      "y": 3.031,
      "z": 3.997
    }
  },
  {
    "id": "Bed_King",
    "file": "Bed_King.glb",
    "category": "Bed",
    "dims": {
      "x": 3.064,
      "y": 1.215,
      "z": 3.953
    }
  },
  {
    "id": "Bed_Single",
    "file": "Bed_Single.glb",
    "category": "Bed",
    "dims": {
      "x": 1.979,
      "y": 1.355,
      "z": 3.94
    }
  },
  {
    "id": "Bookshelf",
    "file": "Bookshelf.glb",
    "category": "Bookshelf",
    "dims": {
      "x": 2.318,
      "y": 4.438,
      "z": 0.756
    }
  },
  {
    "id": "Carpet_1",
    "file": "Carpet_1.glb",
    "category": "Carpet",
    "dims": {
      "x": 2.131,
      "y": 0.037,
      "z": 3.093
    }
  },
  {
    "id": "Carpet_2",
    "file": "Carpet_2.glb",
    "category": "Carpet",
    "dims": {
      "x": 3.093,
      "y": 0.037,
      "z": 3.181
    }
  },
  {
    "id": "Carpet_Round",
    "file": "Carpet_Round.glb",
    "category": "Carpet",
    "dims": {
      "x": 2.493,
      "y": 0.016,
      "z": 2.531
    }
  },
  {
    "id": "Chair_1",
    "file": "Chair_1.glb",
    "category": "Chair",
    "dims": {
      "x": 0.762,
      "y": 1.768,
      "z": 0.825
    }
  },
  {
    "id": "Chair_2",
    "file": "Chair_2.glb",
    "category": "Chair",
    "dims": {
      "x": 0.762,
      "y": 1.689,
      "z": 0.825
    }
  },
  {
    "id": "Chair_3",
    "file": "Chair_3.glb",
    "category": "Chair",
    "dims": {
      "x": 0.762,
      "y": 1.694,
      "z": 0.838
    }
  },
  {
    "id": "Chair_4",
    "file": "Chair_4.glb",
    "category": "Chair",
    "dims": {
      "x": 0.762,
      "y": 1.768,
      "z": 0.825
    }
  },
  {
    "id": "Column_Round1",
    "file": "Column_Round1.glb",
    "category": "Column",
    "dims": {
      "x": 1.4,
      "y": 1.773,
      "z": 1.472
    }
  },
  {
    "id": "Column_Round2",
    "file": "Column_Round2.glb",
    "category": "Column",
    "dims": {
      "x": 1.4,
      "y": 4.001,
      "z": 1.472
    }
  },
  {
    "id": "Column_Round3",
    "file": "Column_Round3.glb",
    "category": "Column",
    "dims": {
      "x": 1.4,
      "y": 5.429,
      "z": 1.472
    }
  },
  {
    "id": "Column_SquareBig",
    "file": "Column_SquareBig.glb",
    "category": "Column",
    "dims": {
      "x": 0.907,
      "y": 4.159,
      "z": 0.907
    }
  },
  {
    "id": "Column_SquareSmall",
    "file": "Column_SquareSmall.glb",
    "category": "Column",
    "dims": {
      "x": 0.907,
      "y": 2.447,
      "z": 0.907
    }
  },
  {
    "id": "Couch_L",
    "file": "Couch_L.glb",
    "category": "Couch",
    "dims": {
      "x": 5.614,
      "y": 2.261,
      "z": 4.327
    }
  },
  {
    "id": "Couch_Large1",
    "file": "Couch_Large1.glb",
    "category": "Couch",
    "dims": {
      "x": 5.475,
      "y": 2.106,
      "z": 1.992
    }
  },
  {
    "id": "Couch_Large2",
    "file": "Couch_Large2.glb",
    "category": "Couch",
    "dims": {
      "x": 5.191,
      "y": 2.108,
      "z": 1.992
    }
  },
  {
    "id": "Couch_Large3",
    "file": "Couch_Large3.glb",
    "category": "Couch",
    "dims": {
      "x": 7.085,
      "y": 1.088,
      "z": 3.022
    }
  },
  {
    "id": "Couch_Medium1",
    "file": "Couch_Medium1.glb",
    "category": "Couch",
    "dims": {
      "x": 4.688,
      "y": 1.91,
      "z": 2.203
    }
  },
  {
    "id": "Couch_Medium2",
    "file": "Couch_Medium2.glb",
    "category": "Couch",
    "dims": {
      "x": 4.519,
      "y": 1.959,
      "z": 1.999
    }
  },
  {
    "id": "Couch_Small1",
    "file": "Couch_Small1.glb",
    "category": "Couch",
    "dims": {
      "x": 2.885,
      "y": 1.91,
      "z": 2.203
    }
  },
  {
    "id": "Couch_Small2",
    "file": "Couch_Small2.glb",
    "category": "Couch",
    "dims": {
      "x": 2.114,
      "y": 1.269,
      "z": 1.992
    }
  },
  {
    "id": "Curtains_Double",
    "file": "Curtains_Double.glb",
    "category": "Curtains",
    "dims": {
      "x": 3.469,
      "y": 4.344,
      "z": 0.476
    }
  },
  {
    "id": "Curtains_Single",
    "file": "Curtains_Single.glb",
    "category": "Curtains",
    "dims": {
      "x": 1.632,
      "y": 4.344,
      "z": 0.476
    }
  },
  {
    "id": "Door_1",
    "file": "Door_1.glb",
    "category": "Door",
    "dims": {
      "x": 1.736,
      "y": 4.188,
      "z": 0.42
    }
  },
  {
    "id": "Door_2",
    "file": "Door_2.glb",
    "category": "Door",
    "dims": {
      "x": 1.74,
      "y": 4.198,
      "z": 0.421
    }
  },
  {
    "id": "Door_3",
    "file": "Door_3.glb",
    "category": "Door",
    "dims": {
      "x": 1.736,
      "y": 4.188,
      "z": 0.416
    }
  },
  {
    "id": "Door_4",
    "file": "Door_4.glb",
    "category": "Door",
    "dims": {
      "x": 1.74,
      "y": 4.198,
      "z": 0.421
    }
  },
  {
    "id": "Door_5",
    "file": "Door_5.glb",
    "category": "Door",
    "dims": {
      "x": 1.74,
      "y": 4.198,
      "z": 0.421
    }
  },
  {
    "id": "Door_6",
    "file": "Door_6.glb",
    "category": "Door",
    "dims": {
      "x": 1.74,
      "y": 4.198,
      "z": 0.421
    }
  },
  {
    "id": "Door_7",
    "file": "Door_7.glb",
    "category": "Door",
    "dims": {
      "x": 1.74,
      "y": 4.198,
      "z": 0.421
    }
  },
  {
    "id": "Door_8",
    "file": "Door_8.glb",
    "category": "Door",
    "dims": {
      "x": 1.74,
      "y": 4.198,
      "z": 0.442
    }
  },
  {
    "id": "Door_9",
    "file": "Door_9.glb",
    "category": "Door",
    "dims": {
      "x": 1.74,
      "y": 4.198,
      "z": 0.421
    }
  },
  {
    "id": "Door_Double",
    "file": "Door_Double.glb",
    "category": "Door",
    "dims": {
      "x": 3.483,
      "y": 4.188,
      "z": 0.43
    }
  },
  {
    "id": "Drawer_1",
    "file": "Drawer_1.glb",
    "category": "Drawer",
    "dims": {
      "x": 2.794,
      "y": 1.353,
      "z": 1.119
    }
  },
  {
    "id": "Drawer_2",
    "file": "Drawer_2.glb",
    "category": "Drawer",
    "dims": {
      "x": 4.035,
      "y": 1.305,
      "z": 1.119
    }
  },
  {
    "id": "Drawer_3",
    "file": "Drawer_3.glb",
    "category": "Drawer",
    "dims": {
      "x": 4.153,
      "y": 1.577,
      "z": 1.336
    }
  },
  {
    "id": "Drawer_4",
    "file": "Drawer_4.glb",
    "category": "Drawer",
    "dims": {
      "x": 2.794,
      "y": 2.07,
      "z": 1.119
    }
  },
  {
    "id": "Drawer_5",
    "file": "Drawer_5.glb",
    "category": "Drawer",
    "dims": {
      "x": 2.794,
      "y": 1.332,
      "z": 1.153
    }
  },
  {
    "id": "Fireplace",
    "file": "Fireplace.glb",
    "category": "Fireplace",
    "dims": {
      "x": 3.25,
      "y": 2.561,
      "z": 1.158
    }
  },
  {
    "id": "Fork",
    "file": "Fork.glb",
    "category": "Fork",
    "dims": {
      "x": 0.045,
      "y": 0.01,
      "z": 0.403
    }
  },
  {
    "id": "Houseplant_1",
    "file": "Houseplant_1.glb",
    "category": "Houseplant",
    "dims": {
      "x": 0.769,
      "y": 0.717,
      "z": 0.694
    }
  },
  {
    "id": "Houseplant_2",
    "file": "Houseplant_2.glb",
    "category": "Houseplant",
    "dims": {
      "x": 0.251,
      "y": 0.385,
      "z": 0.251
    }
  },
  {
    "id": "Houseplant_3",
    "file": "Houseplant_3.glb",
    "category": "Houseplant",
    "dims": {
      "x": 0.343,
      "y": 0.845,
      "z": 0.338
    }
  },
  {
    "id": "Houseplant_4",
    "file": "Houseplant_4.glb",
    "category": "Houseplant",
    "dims": {
      "x": 0.338,
      "y": 0.928,
      "z": 0.338
    }
  },
  {
    "id": "Houseplant_5",
    "file": "Houseplant_5.glb",
    "category": "Houseplant",
    "dims": {
      "x": 0.512,
      "y": 0.424,
      "z": 0.528
    }
  },
  {
    "id": "Houseplant_6",
    "file": "Houseplant_6.glb",
    "category": "Houseplant",
    "dims": {
      "x": 1.04,
      "y": 0.959,
      "z": 1.05
    }
  },
  {
    "id": "Houseplant_7",
    "file": "Houseplant_7.glb",
    "category": "Houseplant",
    "dims": {
      "x": 1.166,
      "y": 0.882,
      "z": 1.22
    }
  },
  {
    "id": "Houseplant_8",
    "file": "Houseplant_8.glb",
    "category": "Houseplant",
    "dims": {
      "x": 0.517,
      "y": 1.557,
      "z": 0.517
    }
  },
  {
    "id": "Kitchen_1Drawers",
    "file": "Kitchen_1Drawers.glb",
    "category": "Kitchen",
    "dims": {
      "x": 1.011,
      "y": 1.614,
      "z": 1.12
    }
  },
  {
    "id": "Kitchen_2Drawers",
    "file": "Kitchen_2Drawers.glb",
    "category": "Kitchen",
    "dims": {
      "x": 1.011,
      "y": 1.625,
      "z": 1.12
    }
  },
  {
    "id": "Kitchen_3Drawers",
    "file": "Kitchen_3Drawers.glb",
    "category": "Kitchen",
    "dims": {
      "x": 1.011,
      "y": 1.625,
      "z": 1.12
    }
  },
  {
    "id": "Kitchen_Cabinet1",
    "file": "Kitchen_Cabinet1.glb",
    "category": "Kitchen",
    "dims": {
      "x": 1.011,
      "y": 1.567,
      "z": 1.071
    }
  },
  {
    "id": "Kitchen_Cabinet2",
    "file": "Kitchen_Cabinet2.glb",
    "category": "Kitchen",
    "dims": {
      "x": 1.011,
      "y": 1.567,
      "z": 1.071
    }
  },
  {
    "id": "Kitchen_CabinetSmall",
    "file": "Kitchen_CabinetSmall.glb",
    "category": "Kitchen",
    "dims": {
      "x": 0.861,
      "y": 0.947,
      "z": 1.071
    }
  },
  {
    "id": "Kitchen_Fridge",
    "file": "Kitchen_Fridge.glb",
    "category": "Kitchen",
    "dims": {
      "x": 1.298,
      "y": 3.308,
      "z": 1.302
    }
  },
  {
    "id": "Kitchen_Oven",
    "file": "Kitchen_Oven.glb",
    "category": "Kitchen",
    "dims": {
      "x": 1.011,
      "y": 1.617,
      "z": 1.12
    }
  },
  {
    "id": "Kitchen_Oven_Large",
    "file": "Kitchen_Oven_Large.glb",
    "category": "Kitchen",
    "dims": {
      "x": 1.171,
      "y": 1.593,
      "z": 1.07
    }
  },
  {
    "id": "Kitchen_Sink",
    "file": "Kitchen_Sink.glb",
    "category": "Kitchen",
    "dims": {
      "x": 1.011,
      "y": 1.924,
      "z": 1.12
    }
  },
  {
    "id": "Knife",
    "file": "Knife.glb",
    "category": "Knife",
    "dims": {
      "x": 0.035,
      "y": 0.007,
      "z": 0.419
    }
  },
  {
    "id": "Light_Ceiling1",
    "file": "Light_Ceiling1.glb",
    "category": "Light",
    "dims": {
      "x": 0.441,
      "y": 0.822,
      "z": 0.436
    }
  },
  {
    "id": "Light_Ceiling2",
    "file": "Light_Ceiling2.glb",
    "category": "Light",
    "dims": {
      "x": 0.361,
      "y": 1.012,
      "z": 0.357
    }
  },
  {
    "id": "Light_Ceiling3",
    "file": "Light_Ceiling3.glb",
    "category": "Light",
    "dims": {
      "x": 0.537,
      "y": 0.678,
      "z": 0.537
    }
  },
  {
    "id": "Light_Ceiling4",
    "file": "Light_Ceiling4.glb",
    "category": "Light",
    "dims": {
      "x": 0.776,
      "y": 1.297,
      "z": 0.776
    }
  },
  {
    "id": "Light_Ceiling5",
    "file": "Light_Ceiling5.glb",
    "category": "Light",
    "dims": {
      "x": 0.531,
      "y": 0.136,
      "z": 0.558
    }
  },
  {
    "id": "Light_Ceiling6",
    "file": "Light_Ceiling6.glb",
    "category": "Light",
    "dims": {
      "x": 0.531,
      "y": 0.129,
      "z": 0.558
    }
  },
  {
    "id": "Light_CeilingSingle",
    "file": "Light_CeilingSingle.glb",
    "category": "Light",
    "dims": {
      "x": 0.264,
      "y": 0.478,
      "z": 0.278
    }
  },
  {
    "id": "Light_Chandelier",
    "file": "Light_Chandelier.glb",
    "category": "Light",
    "dims": {
      "x": 0.813,
      "y": 0.519,
      "z": 0.813
    }
  },
  {
    "id": "Light_Cube",
    "file": "Light_Cube.glb",
    "category": "Light",
    "dims": {
      "x": 0.564,
      "y": 1.035,
      "z": 0.564
    }
  },
  {
    "id": "Light_Cube2",
    "file": "Light_Cube2.glb",
    "category": "Light",
    "dims": {
      "x": 0.554,
      "y": 0.922,
      "z": 0.641
    }
  },
  {
    "id": "Light_Desk",
    "file": "Light_Desk.glb",
    "category": "Light",
    "dims": {
      "x": 0.252,
      "y": 0.573,
      "z": 0.453
    }
  },
  {
    "id": "Light_Floor1",
    "file": "Light_Floor1.glb",
    "category": "Light",
    "dims": {
      "x": 0.281,
      "y": 1.603,
      "z": 0.295
    }
  },
  {
    "id": "Light_Floor2",
    "file": "Light_Floor2.glb",
    "category": "Light",
    "dims": {
      "x": 0.313,
      "y": 0.757,
      "z": 0.329
    }
  },
  {
    "id": "Light_Floor3",
    "file": "Light_Floor3.glb",
    "category": "Light",
    "dims": {
      "x": 0.4,
      "y": 0.894,
      "z": 0.421
    }
  },
  {
    "id": "Light_Floor4",
    "file": "Light_Floor4.glb",
    "category": "Light",
    "dims": {
      "x": 0.351,
      "y": 0.763,
      "z": 0.351
    }
  },
  {
    "id": "Light_Icosahedron",
    "file": "Light_Icosahedron.glb",
    "category": "Light",
    "dims": {
      "x": 0.502,
      "y": 0.88,
      "z": 0.479
    }
  },
  {
    "id": "Light_Icosahedron2",
    "file": "Light_Icosahedron2.glb",
    "category": "Light",
    "dims": {
      "x": 1.626,
      "y": 0.88,
      "z": 0.502
    }
  },
  {
    "id": "Light_Small",
    "file": "Light_Small.glb",
    "category": "Light",
    "dims": {
      "x": 0.155,
      "y": 0.106,
      "z": 0.163
    }
  },
  {
    "id": "Light_Stand1",
    "file": "Light_Stand1.glb",
    "category": "Light",
    "dims": {
      "x": 0.773,
      "y": 2.994,
      "z": 0.813
    }
  },
  {
    "id": "Light_Stand2",
    "file": "Light_Stand2.glb",
    "category": "Light",
    "dims": {
      "x": 0.678,
      "y": 2.945,
      "z": 0.678
    }
  },
  {
    "id": "NightStand_1",
    "file": "NightStand_1.glb",
    "category": "NightStand",
    "dims": {
      "x": 0.952,
      "y": 0.825,
      "z": 0.952
    }
  },
  {
    "id": "NightStand_2",
    "file": "NightStand_2.glb",
    "category": "NightStand",
    "dims": {
      "x": 0.952,
      "y": 0.945,
      "z": 0.952
    }
  },
  {
    "id": "NightStand_3",
    "file": "NightStand_3.glb",
    "category": "NightStand",
    "dims": {
      "x": 0.952,
      "y": 0.827,
      "z": 0.952
    }
  },
  {
    "id": "Plate_1",
    "file": "Plate_1.glb",
    "category": "Plate",
    "dims": {
      "x": 0.374,
      "y": 0.032,
      "z": 0.393
    }
  },
  {
    "id": "Plate_2",
    "file": "Plate_2.glb",
    "category": "Plate",
    "dims": {
      "x": 0.352,
      "y": 0.025,
      "z": 0.352
    }
  },
  {
    "id": "Plate_3",
    "file": "Plate_3.glb",
    "category": "Plate",
    "dims": {
      "x": 0.374,
      "y": 0.035,
      "z": 0.393
    }
  },
  {
    "id": "Shelf_1",
    "file": "Shelf_1.glb",
    "category": "Shelf",
    "dims": {
      "x": 0.707,
      "y": 3.167,
      "z": 0.652
    }
  },
  {
    "id": "Shelf_2",
    "file": "Shelf_2.glb",
    "category": "Shelf",
    "dims": {
      "x": 1.119,
      "y": 4.438,
      "z": 0.756
    }
  },
  {
    "id": "Shelf_Large",
    "file": "Shelf_Large.glb",
    "category": "Shelf",
    "dims": {
      "x": 3.381,
      "y": 4.438,
      "z": 0.756
    }
  },
  {
    "id": "Shelf_Small1",
    "file": "Shelf_Small1.glb",
    "category": "Shelf",
    "dims": {
      "x": 1.944,
      "y": 0.577,
      "z": 0.55
    }
  },
  {
    "id": "Shelf_Small2",
    "file": "Shelf_Small2.glb",
    "category": "Shelf",
    "dims": {
      "x": 1.04,
      "y": 0.39,
      "z": 0.55
    }
  },
  {
    "id": "Shelf_Small3",
    "file": "Shelf_Small3.glb",
    "category": "Shelf",
    "dims": {
      "x": 1.04,
      "y": 0.39,
      "z": 0.55
    }
  },
  {
    "id": "Spoon",
    "file": "Spoon.glb",
    "category": "Spoon",
    "dims": {
      "x": 0.084,
      "y": 0.018,
      "z": 0.405
    }
  },
  {
    "id": "Stool",
    "file": "Stool.glb",
    "category": "Stool",
    "dims": {
      "x": 0.675,
      "y": 1.372,
      "z": 0.71
    }
  },
  {
    "id": "Table_RoundLarge",
    "file": "Table_RoundLarge.glb",
    "category": "Table",
    "dims": {
      "x": 3.713,
      "y": 1.121,
      "z": 1.941
    }
  },
  {
    "id": "Table_RoundSmall",
    "file": "Table_RoundSmall.glb",
    "category": "Table",
    "dims": {
      "x": 1.941,
      "y": 1.147,
      "z": 1.941
    }
  },
  {
    "id": "Table_RoundSmall2",
    "file": "Table_RoundSmall2.glb",
    "category": "Table",
    "dims": {
      "x": 1.941,
      "y": 1.208,
      "z": 1.941
    }
  },
  {
    "id": "Trashcan_Cylindric",
    "file": "Trashcan_Cylindric.glb",
    "category": "Trashcan",
    "dims": {
      "x": 0.755,
      "y": 1.074,
      "z": 0.755
    }
  },
  {
    "id": "Trashcan_Green",
    "file": "Trashcan_Green.glb",
    "category": "Trashcan",
    "dims": {
      "x": 1.217,
      "y": 2.211,
      "z": 1.591
    }
  },
  {
    "id": "Trashcan_Large",
    "file": "Trashcan_Large.glb",
    "category": "Trashcan",
    "dims": {
      "x": 1.223,
      "y": 1.846,
      "z": 1.223
    }
  },
  {
    "id": "Trashcan_Small1",
    "file": "Trashcan_Small1.glb",
    "category": "Trashcan",
    "dims": {
      "x": 0.503,
      "y": 0.712,
      "z": 0.306
    }
  },
  {
    "id": "Trashcan_Small2",
    "file": "Trashcan_Small2.glb",
    "category": "Trashcan",
    "dims": {
      "x": 0.465,
      "y": 0.56,
      "z": 0.428
    }
  },
  {
    "id": "Window_Large1",
    "file": "Window_Large1.glb",
    "category": "Window",
    "dims": {
      "x": 1.832,
      "y": 1.698,
      "z": 0.141
    }
  },
  {
    "id": "Window_Large2",
    "file": "Window_Large2.glb",
    "category": "Window",
    "dims": {
      "x": 1.832,
      "y": 1.698,
      "z": 0.141
    }
  },
  {
    "id": "Window_Round1",
    "file": "Window_Round1.glb",
    "category": "Window",
    "dims": {
      "x": 0.906,
      "y": 1.55,
      "z": 0.113
    }
  },
  {
    "id": "Window_Round2",
    "file": "Window_Round2.glb",
    "category": "Window",
    "dims": {
      "x": 0.906,
      "y": 1.55,
      "z": 0.113
    }
  },
  {
    "id": "Window_Round3",
    "file": "Window_Round3.glb",
    "category": "Window",
    "dims": {
      "x": 0.906,
      "y": 1.55,
      "z": 0.113
    }
  },
  {
    "id": "Window_Small1",
    "file": "Window_Small1.glb",
    "category": "Window",
    "dims": {
      "x": 0.928,
      "y": 1.238,
      "z": 0.141
    }
  },
  {
    "id": "Window_Small2",
    "file": "Window_Small2.glb",
    "category": "Window",
    "dims": {
      "x": 0.928,
      "y": 1.238,
      "z": 0.141
    }
  },
  {
    "id": "Window_Small3",
    "file": "Window_Small3.glb",
    "category": "Window",
    "dims": {
      "x": 0.928,
      "y": 1.238,
      "z": 0.141
    }
  }
] as const;
