import { INTERIOR_MODELS } from './catalog.data';

/**
 * One interior model from the Quaternius "Ultimate House Interior" CC0 pack
 * (see PROVENANCE.md). The GLBs live under `public/models/interior/`; the
 * manifest in `catalog.data.ts` is generated by `scripts/convert-interior.cjs`.
 */
export interface InteriorModelEntry {
  /** Stable id = source filename stem, e.g. `Bathroom_Bathtub`. */
  readonly id: string;
  /** GLB filename under `public/models/interior/`. */
  readonly file: string;
  /** Category = id prefix before the first underscore, e.g. `Bathroom`. */
  readonly category: string;
  /** Bounding-box size in source units (normalized to the grid by the registry). */
  readonly dims: { readonly x: number; readonly y: number; readonly z: number };
}

/** The full interior-model catalog. */
export const interiorModels: readonly InteriorModelEntry[] =
  INTERIOR_MODELS as readonly InteriorModelEntry[];

/** Look up a model by id; `undefined` if unknown. */
export function interiorModelById(id: string): InteriorModelEntry | undefined {
  return interiorModels.find((m) => m.id === id);
}

/** All distinct categories present in the catalog, sorted. */
export function interiorCategories(): string[] {
  return [...new Set(interiorModels.map((m) => m.category))].sort();
}
